-- Create CARD table (H2 compatible)
CREATE TABLE IF NOT EXISTS card (
   card_number VARCHAR(16) PRIMARY KEY,
   pin         VARCHAR(4),
   balance     DECIMAL(10,2),
   id          INT GENERATED BY DEFAULT AS IDENTITY,
   owner_name  VARCHAR(50),
   pin_hash    VARCHAR(256)
);

-- Insert sample cards with hashed PINs
INSERT INTO card (card_number, pin, balance, owner_name, pin_hash) VALUES
('4123456789012345', NULL, 1500.00, 'Alice', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4'), -- PIN 1234
('4123456789012346', NULL, 50.00, 'Bob', 'fe2592b42a727e977f055947385b709cc82b16b9a87f88c6abf3900d65d0cdc3'),   -- PIN 0000
('5123456789012345', NULL, 500.00, 'Eve', '9af15b336e6a9619928537df30b2e6a2376569fcf9d7e773eccede65606529a0'),  -- PIN 1111
('6123456789012345', NULL, 2000.00, 'David', '8d969eef6ecad3c29a3a629280e686cff8ca7d9057c8e0c4b45d4a9e3a5a1a1d'), -- PIN 123456
('7123456789012345', NULL, 100.00, 'Fiona', 'ef797c8118f02d4c602e51815f7ed9bb62a3c9f24ad0eebec1db0c03f63b9d8b'); -- PIN 0001
